clear all
clc

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('C:\Users\cipri\Desktop\Phyton ROMs for COMSOL 5.5\mark2');

model.param.set('input1', '0.3 [W]');
model.param.set('input2', '0.4 [W]');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.result.table.create('tbl1', 'Table');
model.result.table.create('evl3', 'Table');

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').create('cyl1', 'Cylinder');
model.component('comp1').geom('geom1').feature('cyl1').set('pos', {'50 [mm]' '50 [mm]' '0'});
model.component('comp1').geom('geom1').feature('cyl1').set('r', '50 [mm]');
model.component('comp1').geom('geom1').feature('cyl1').set('h', '3 [mm]');
model.component('comp1').geom('geom1').create('wp1', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp1').set('quickz', '3 [mm]');
model.component('comp1').geom('geom1').feature('wp1').set('unite', true);
model.component('comp1').geom('geom1').feature('wp1').geom.create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r1').label('Heat Source');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r1').set('selresult', true);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r1').set('pos', [0.02 0.02]);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r1').set('size', [0.01 0.02]);
model.component('comp1').geom('geom1').feature('wp1').geom.create('r2', 'Rectangle');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r2').label('Heat Source 2');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r2').set('selresult', true);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r2').set('pos', [0.05 0.06]);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('r2').set('size', [0.03 0.01]);
model.component('comp1').geom('geom1').run;

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material.create('mat2', 'Common');
model.component('comp1').material('mat1').propertyGroup.create('AroraMobilityModel', 'Arora mobility model');
model.component('comp1').material('mat1').propertyGroup.create('PowerLawMobilityModel', 'Power law mobility model');
model.component('comp1').material('mat1').propertyGroup.create('Auger', 'Auger recombination');
model.component('comp1').material('mat1').propertyGroup.create('Direct', 'Direct recombination');
model.component('comp1').material('mat1').propertyGroup.create('SRH', 'Shockley-Read-Hall recombination');
model.component('comp1').material('mat1').propertyGroup.create('FletcherMobilityModel', 'Fletcher mobility model');
model.component('comp1').material('mat1').propertyGroup.create('CaugheyThomasMobilityModel', 'Caughey-Thomas mobility model');
model.component('comp1').material('mat1').propertyGroup.create('SemicondMaterial', 'Semiconductor material');
model.component('comp1').material('mat1').propertyGroup.create('LombardiSurfaceMobilityModel', 'Lombardi surface mobility model');
model.component('comp1').material('mat1').propertyGroup.create('ImpactIonization', 'Impact ionization');
model.component('comp1').material('mat1').propertyGroup.create('SlotboomModel', 'Slotboom model');
model.component('comp1').material('mat1').propertyGroup.create('JainRoulstonModel', 'Jain-Roulston model');
model.component('comp1').material('mat2').selection.all;
model.component('comp1').material('mat2').propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat2').propertyGroup.create('Murnaghan', 'Murnaghan');
model.component('comp1').material('mat2').propertyGroup.create('Lame', ['Lam' native2unicode(hex2dec({'00' 'e9'}), 'unicode') ' parameters']);

model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');
model.component('comp1').physics('ht').create('sar1', 'SurfaceToAmbientRadiation', 2);
model.component('comp1').physics('ht').feature('sar1').selection.set([1 2 4 6 8]);
model.component('comp1').physics('ht').create('hf1', 'HeatFluxBoundary', 2);
model.component('comp1').physics('ht').feature('hf1').selection.set([5]);
model.component('comp1').physics('ht').create('hf2', 'HeatFluxBoundary', 2);
model.component('comp1').physics('ht').feature('hf2').selection.set([7]);

model.component('comp1').mesh('mesh1').create('ftet1', 'FreeTet');

model.component('comp1').probe.create('pdom1', 'DomainPoint');
model.component('comp1').probe.create('pdom2', 'DomainPoint');
model.component('comp1').probe.create('pdom3', 'DomainPoint');

model.result.table('tbl1').label('Probe Table 1');
model.result.table('evl3').label('Evaluation 3D');
model.result.table('evl3').comments('Interactive 3D values');

model.component('comp1').view('view2').axis.set('xmin', -0.014326464384794235);
model.component('comp1').view('view2').axis.set('xmax', 0.11432646960020065);
model.component('comp1').view('view2').axis.set('ymin', -0.004999998956918716);
model.component('comp1').view('view2').axis.set('ymax', 0.10500000417232513);

model.component('comp1').material('mat1').active(false);
model.component('comp1').material('mat1').label('Si - Silicon');
model.component('comp1').material('mat1').propertyGroup('def').set('relpermittivity', {'11.7' '0' '0' '0' '11.7' '0' '0' '0' '11.7'});
model.component('comp1').material('mat1').propertyGroup('def').descr('relpermittivity_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'131[W/(m*K)]' '0' '0' '0' '131[W/(m*K)]' '0' '0' '0' '131[W/(m*K)]'});
model.component('comp1').material('mat1').propertyGroup('def').descr('thermalconductivity_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('def').set('density', '2329[kg/m^3]');
model.component('comp1').material('mat1').propertyGroup('def').descr('density_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', '700[J/(kg*K)]');
model.component('comp1').material('mat1').propertyGroup('def').descr('heatcapacity_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun_min_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup_min_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Nn0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Np0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('alpha0_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta1_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta2_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta3_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta4_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Tref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun_min_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup_min_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Nn0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Np0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('alpha0_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta1_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta2_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta3_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta4_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Tref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun_min_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup_min_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Nn0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Np0_ref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('alpha0_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta1_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta2_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta3_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta4_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Tref_arora', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun0_ref_arora', '1252[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup0_ref_arora', '407[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mun_min_ref_arora', '88[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('mup_min_ref_arora', '54.3[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Nn0_ref_arora', '1.26e17[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Np0_ref_arora', '2.35e17[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('alpha0_arora', '0.88');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta1_arora', '-0.57');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta2_arora', '-2.33');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta3_arora', '-2.33');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('beta4_arora', '-0.146');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').set('Tref_arora', '300[K]');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('mun0_ref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('mup0_ref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('mun_min_ref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('mup_min_ref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('Nn0_ref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('Np0_ref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('alpha0_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('beta1_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('beta2_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('beta3_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('beta4_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('AroraMobilityModel').descr('Tref_arora_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mun0_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mup0_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphan_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphap_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('Tref_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mun0_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mup0_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphan_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphap_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('Tref_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mun0_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mup0_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphan_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphap_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('Tref_pl', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mun0_pl', '1448[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('mup0_pl', '473[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphan_pl', '2.33');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('alphap_pl', '2.23');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').set('Tref_pl', '300[K]');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').descr('mun0_pl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').descr('mup0_pl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').descr('alphan_pl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').descr('alphap_pl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('PowerLawMobilityModel').descr('Tref_pl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cn', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cp', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cn', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cp', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cn', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cp', '');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cn', '2.8e-31[cm^6/s]');
model.component('comp1').material('mat1').propertyGroup('Auger').set('Cp', '9.9e-32[cm^6/s]');
model.component('comp1').material('mat1').propertyGroup('Auger').descr('Cn_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('Auger').descr('Cp_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('Direct').set('C', '0[cm^3/s]');
model.component('comp1').material('mat1').propertyGroup('Direct').descr('C_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taun', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taup', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taun', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taup', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taun', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taup', '');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taun', '10[us]');
model.component('comp1').material('mat1').propertyGroup('SRH').set('taup', '10[us]');
model.component('comp1').material('mat1').propertyGroup('SRH').descr('taun_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SRH').descr('taup_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F1_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F2_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('Tref_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F1_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F2_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('Tref_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F1_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F2_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('Tref_fl', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F1_fl', '1.04e21[1/(cm^1*V*s)]');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('F2_fl', '7.45e13[1/cm^2]');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').set('Tref_fl', '300[K]');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').descr('F1_fl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').descr('F2_fl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('FletcherMobilityModel').descr('Tref_fl_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphan0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphap0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vn0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vp0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan1_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap1_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan2_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap2_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('Tref_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphan0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphap0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vn0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vp0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan1_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap1_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan2_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap2_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('Tref_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphan0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphap0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vn0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vp0_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan1_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap1_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan2_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap2_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('Tref_ct', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphan0_ct', '1.11');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('alphap0_ct', '1.21');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vn0_ct', '1e7[cm/s]');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('vp0_ct', '8.37e6[cm/s]');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan1_ct', '0.66');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap1_ct', '0.17');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betan2_ct', '-0.87');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('betap2_ct', '-0.52');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').set('Tref_ct', '300[K]');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('alphan0_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('alphap0_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('vn0_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('vp0_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('betan1_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('betap1_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('betan2_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('betap2_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('CaugheyThomasMobilityModel').descr('Tref_ct_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Eg0', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('chi0', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nv', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nc', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mun', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mup', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Eg0', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('chi0', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nv', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nc', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mun', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mup', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Eg0', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('chi0', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nv', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nc', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mun', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mup', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Eg0', '1.12[V]');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('chi0', '4.05[V]');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nv', '(T/300[K])^(3/2)*1.04e19[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('Nc', '(T/300[K])^(3/2)*2.8e19[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mun', '1450[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').set('mup', '500[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').descr('Eg0_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').descr('chi0_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').descr('Nv_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').descr('Nc_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').descr('mun_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').descr('mup_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SemicondMaterial').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltan_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltap_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun1_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup1_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun2_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup2_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphan_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphap_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Tref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Eref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Nref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltan_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltap_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun1_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup1_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun2_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup2_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphan_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphap_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Tref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Eref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Nref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltan_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltap_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun1_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup1_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun2_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup2_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphan_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphap_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Tref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Eref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Nref_ls', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltan_ls', '5.82e14[V/s]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('deltap_ls', '2.05e14[V/s]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun1_ls', '4.75e7[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup1_ls', '9.93e7[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mun2_ls', '1.74e5[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('mup2_ls', '8.84e5[cm^2/(V*s)]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphan_ls', '0.125');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('alphap_ls', '0.0317');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Tref_ls', '1[K]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Eref_ls', '1[V/cm]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').set('Nref_ls', '1[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('deltan_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('deltap_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('mun1_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('mup1_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('mun2_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('mup2_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('alphan_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('alphap_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('Tref_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('Eref_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('LombardiSurfaceMobilityModel').descr('Nref_ls_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('an', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('ap', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bn', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bp', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cnii', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cpii', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dn', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dp', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('an', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('ap', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bn', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bp', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cnii', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cpii', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dn', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dp', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('an', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('ap', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bn', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bp', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cnii', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cpii', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dn', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dp', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('an', '0.426');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('ap', '0.243');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bn', '4.81E5[V/cm]');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('bp', '6.53E5[V/cm]');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cnii', '3.05E-4');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('cpii', '5.35E-4');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dn', '6.86E-4');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').set('dp', '5.67E-4');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('an_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('ap_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('bn_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('bp_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('cnii_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('cpii_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('dn_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('ImpactIonization').descr('dp_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Eref_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Nref_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('alpha_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Eref_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Nref_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('alpha_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Eref_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Nref_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('alpha_sb', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Eref_sb', '0.00692[V]');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('Nref_sb', '1.3e17[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').set('alpha_sb', '0.5');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').descr('Eref_sb_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').descr('Nref_sb_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('SlotboomModel').descr('alpha_sb_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('An_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bn_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cn_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Ap_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bp_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cp_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Nref_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('alpha_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('An_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bn_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cn_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Ap_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bp_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cp_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Nref_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('alpha_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('An_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bn_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cn_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Ap_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bp_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cp_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Nref_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('alpha_jr', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('An_jr', '3.5e-8[V]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bn_jr', '0[V]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cn_jr', '0[V]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Ap_jr', '3.5e-8[V]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Bp_jr', '0[V]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Cp_jr', '0[V]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('Nref_jr', '1[1/cm^3]');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').set('alpha_jr', '0.5');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('An_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('Bn_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('Cn_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('Ap_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('Bp_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('Cp_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('Nref_jr_symmetry', '');
model.component('comp1').material('mat1').propertyGroup('JainRoulstonModel').descr('alpha_jr_symmetry', '');
model.component('comp1').material('mat2').label('Aluminum');
model.component('comp1').material('mat2').set('family', 'aluminum');
model.component('comp1').material('mat2').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('def').descr('relpermeability_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('def').set('heatcapacity', '900[J/(kg*K)]');
model.component('comp1').material('mat2').propertyGroup('def').descr('heatcapacity_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('def').set('thermalconductivity', {'238[W/(m*K)]' '0' '0' '0' '238[W/(m*K)]' '0' '0' '0' '238[W/(m*K)]'});
model.component('comp1').material('mat2').propertyGroup('def').descr('thermalconductivity_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('def').set('electricconductivity', {'3.774e7[S/m]' '0' '0' '0' '3.774e7[S/m]' '0' '0' '0' '3.774e7[S/m]'});
model.component('comp1').material('mat2').propertyGroup('def').descr('electricconductivity_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('def').descr('relpermittivity_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('def').set('thermalexpansioncoefficient', {'23e-6[1/K]' '0' '0' '0' '23e-6[1/K]' '0' '0' '0' '23e-6[1/K]'});
model.component('comp1').material('mat2').propertyGroup('def').descr('thermalexpansioncoefficient_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('def').set('density', '2700[kg/m^3]');
model.component('comp1').material('mat2').propertyGroup('def').descr('density_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Enu').set('youngsmodulus', '70e9[Pa]');
model.component('comp1').material('mat2').propertyGroup('Enu').descr('youngsmodulus_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Enu').set('poissonsratio', '0.33');
model.component('comp1').material('mat2').propertyGroup('Enu').descr('poissonsratio_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('l', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('m', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('n', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('l', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('m', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('n', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('l', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('m', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('n', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('l', '-2.5e11[Pa]');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('m', '-3.3e11[Pa]');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').set('n', '-3.5e11[Pa]');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').descr('l_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').descr('m_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Murnaghan').descr('n_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('lambLame', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('muLame', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('lambLame', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('muLame', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('lambLame', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('muLame', '');
model.component('comp1').material('mat2').propertyGroup('Lame').set('lambLame', '5.1e10[Pa]');
model.component('comp1').material('mat2').propertyGroup('Lame').set('muLame', '2.6e10[Pa]');
model.component('comp1').material('mat2').propertyGroup('Lame').descr('lambLame_symmetry', '');
model.component('comp1').material('mat2').propertyGroup('Lame').descr('muLame_symmetry', '');

model.component('comp1').physics('ht').feature('sar1').set('epsilon_rad_mat', 'userdef');
model.component('comp1').physics('ht').feature('sar1').set('epsilon_rad', 0.7);
model.component('comp1').physics('ht').feature('hf1').set('HeatFluxType', 'HeatRate');
model.component('comp1').physics('ht').feature('hf1').set('P0', 'input1');
model.component('comp1').physics('ht').feature('hf2').set('HeatFluxType', 'HeatRate');
model.component('comp1').physics('ht').feature('hf2').set('P0', 'input2');

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 8);
model.component('comp1').mesh('mesh1').feature('size').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size').set('hmin', 0.003);
model.component('comp1').mesh('mesh1').feature('size').set('hgrad', 1.3);
model.component('comp1').mesh('mesh1').run;

model.component('comp1').probe('pdom1').label('Probe 1');
model.component('comp1').probe('pdom1').set('coords3', [0.05 0.05 0.003]);
model.component('comp1').probe('pdom1').feature('ppb1').set('table', 'tbl1');
model.component('comp1').probe('pdom1').feature('ppb1').set('window', 'window1');
model.component('comp1').probe('pdom2').label('Probe 2');
model.component('comp1').probe('pdom2').set('coords3', [0.03 0.07 0.003]);
model.component('comp1').probe('pdom2').feature('ppb2').label('Point Probe Expression 1');
model.component('comp1').probe('pdom2').feature('ppb2').set('table', 'tbl1');
model.component('comp1').probe('pdom2').feature('ppb2').set('window', 'window1');
model.component('comp1').probe('pdom3').label('Probe 3');
model.component('comp1').probe('pdom3').set('coords3', [0.08 0.03 0.003]);
model.component('comp1').probe('pdom3').feature('ppb3').label('Point Probe Expression 1');
model.component('comp1').probe('pdom3').feature('ppb3').set('table', 'tbl1');
model.component('comp1').probe('pdom3').feature('ppb3').set('window', 'window1');

model.study.create('std1');
model.study('std1').create('time', 'Transient');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('t1').create('d1', 'Direct');
model.sol('sol1').feature('t1').create('i1', 'Iterative');
model.sol('sol1').feature('t1').create('i2', 'Iterative');
model.sol('sol1').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature.remove('fcDef');

model.result.dataset.create('dset2', 'Solution');
model.result.dataset.create('cpt1', 'CutPoint3D');
model.result.dataset.create('cpt2', 'CutPoint3D');
model.result.dataset.create('cpt3', 'CutPoint3D');
model.result.dataset('dset2').set('probetag', 'pdom3');
model.result.dataset('cpt1').set('probetag', 'pdom1');
model.result.dataset('cpt1').set('data', 'dset2');
model.result.dataset('cpt2').set('probetag', 'pdom2');
model.result.dataset('cpt2').set('data', 'dset2');
model.result.dataset('cpt3').set('probetag', 'pdom3');
model.result.dataset('cpt3').set('data', 'dset2');
model.result.numerical.create('pev1', 'EvalPoint');
model.result.numerical.create('pev2', 'EvalPoint');
model.result.numerical.create('pev3', 'EvalPoint');
model.result.numerical('pev1').set('probetag', 'pdom1/ppb1');
model.result.numerical('pev2').set('probetag', 'pdom2/ppb2');
model.result.numerical('pev3').set('probetag', 'pdom3/ppb3');
model.result.create('pg1', 'PlotGroup3D');
model.result.create('pg2', 'PlotGroup3D');
model.result.create('pg3', 'PlotGroup1D');
model.result('pg1').create('surf1', 'Surface');
model.result('pg2').create('iso1', 'Isosurface');
model.result('pg3').set('probetag', 'window1');
model.result('pg3').create('tblp1', 'Table');
model.result('pg3').create('glob1', 'Global');
model.result('pg3').feature('tblp1').set('probetag', 'pdom1/ppb1,pdom2/ppb2,pdom3/ppb3');

model.component('comp1').probe('pdom1').genResult([]);
model.component('comp1').probe('pdom2').genResult([]);
model.component('comp1').probe('pdom3').genResult([]);

model.study('std1').feature('time').set('tlist', 'range(0,10,1000)');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('v1').set('clist', {'range(0,10,1000)' '1.0[s]'});
model.sol('sol1').feature('t1').set('tlist', 'range(0,10,1000)');
model.sol('sol1').feature('t1').set('maxorder', 2);
model.sol('sol1').feature('t1').set('estrat', 'exclude');
model.sol('sol1').feature('t1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 50);
model.sol('sol1').feature('t1').feature('fc1').set('damp', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('jtech', 'once');
model.sol('sol1').feature('t1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('t1').feature('fc1').set('aaccdim', 5);
model.sol('sol1').feature('t1').feature('fc1').set('aaccmix', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('aaccdelay', 1);
model.sol('sol1').feature('t1').feature('d1').label('Direct, Heat Transfer Variables (ht)');
model.sol('sol1').feature('t1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('t1').feature('i1').label('AMG, Heat Transfer Variables (ht)');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('i2').label('GMG, Heat Transfer Variables (ht)');
model.sol('sol1').feature('t1').feature('i2').set('rhob', 20);
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').runAll;

model.result.dataset('dset2').label('Probe Solution 2');
model.result.dataset('dset2').set('frametype', 'spatial');
model.result.dataset('cpt1').set('data', 'dset2');
model.result.dataset('cpt2').set('data', 'dset2');
model.result.dataset('cpt3').set('data', 'dset2');
model.result.dataset.remove('dset3');
model.result('pg1').label('Temperature (ht)');
model.result('pg1').feature('surf1').label('Surface');
model.result('pg1').feature('surf1').set('colortable', 'ThermalLight');
model.result('pg1').feature('surf1').set('resolution', 'normal');
model.result('pg2').label('Isothermal Contours (ht)');
model.result('pg2').set('looplevel', [1]);
model.result('pg2').feature('iso1').label('Isosurface');
model.result('pg2').feature('iso1').set('number', 10);
model.result('pg2').feature('iso1').set('levelrounding', false);
model.result('pg2').feature('iso1').set('colortable', 'ThermalLight');
model.result('pg2').feature('iso1').set('resolution', 'normal');
model.result('pg3').label('Probe Plot Group 3');
model.result('pg3').set('data', 'cpt1');
model.result('pg3').set('looplevelinput', {'all'});
model.result('pg3').set('xlabel', 'Time (s)');
model.result('pg3').set('windowtitle', 'Probe Plot 1');
model.result('pg3').set('xlabelactive', false);
model.result('pg3').feature('tblp1').label('Probe Table Graph 1');
model.result('pg3').feature('tblp1').set('legend', true);
model.result('pg3').feature('glob1').set('data', 'none');
model.result('pg3').feature('glob1').set('expr', {'ppb1' 'ppb2' 'ppb3'});
model.result('pg3').feature('glob1').set('unit', {'degC' 'degC' 'degC'});
model.result('pg3').feature('glob1').set('descr', {'' '' ''});


% Extract the matrices of the state-space model from th COMSOL model
M = mphstate(model, 'sol1', 'out', {'Mc' 'MA' 'MB' 'C' 'D' 'x0', 'Null' 'ud'}, ...
    'input', {'input1', 'input2'}, 'output', {'comp1.ppb1', 'comp1.ppb2', 'comp1.ppb3'}, 'sparse', 'on', 'keepfeature', 'on', 'initmethod', 'init', 'initsol', 'zero');

% Rename the matrices
E=M.Mc; A=M.MA; B=M.MB; C=M.C; x0=M.x0; NullMatrix=M.Null; udVector=M.ud;

% Save the matrices on a file .mat 
save('matrices.mat', 'E', 'A', 'B', 'C', 'x0');

